### ISSUE TITLE
Future events missing in calendar

### ISSUE THREAD

**Issue by Boby360** [othyn/go-calendar#10]
### Description

Looking at the Calendar on my phone, as well as on my desktop in Outlook, I don't see upcoming events farther in the future.

I see Goomy and Cynaquil CD days in the future, but no spotlight hour or raid hour.

Typically I would assume user error, and that the files were not properly imported, resulting in not getting new data.
I however have not touched anything related to this in many months.

I don't know what distance into the future it is designed to load, and if the user has control of that, but it seems weird and thought I would bring it up.

I see spotlight hour for today, and raid hour for tomorrow, and I am curious to see if the next set appears after one is done.
The fact that I am pretty sure this has been working properly for awhile (I think?) and now isn't loading things in the ICS files, just makes me wonder. Has there been changes?

### Version

Unknown

### Steps to Reproduce

Look on phone or outlook.

### Device

Samsung S23

### Operating System

Android 14

**Comment by Boby360** [comment]
Ok, I think things are maybe working just fine...

The release before the most recent one, seems to only have the data in my calendar, so it would just be the matter of waiting for the refresh event...

**Comment by othyn** [comment]
👍 This repo just tracks and publishes event listings from https://leekduck.com/events/. Given how new those events are, I'm guessing they'll trickle through to this repo within a day or so, as they appear to now be published on LeekDuck as 'new' events. A new build is run every night, so the longest you'd ever be waiting would be a maximum of 24 hours.

LeekDuck tends to publish stuff for the season within a few hours of its announcement, and thats about as far into the future as you can get. This as Niantic tend to leave announcements of dates and events until the last minute.
