### ISSUE TITLE
Missing Mega Lucario Raid Day

### ISSUE THREAD

**Issue by ArmandAgopian** [othyn/go-calendar#11]
### Description

LeekDuck reports Mega Lucario on July 27 but Go Calendar is not showing it. Last calendar update was 3 months ago.

### Version

2.4.163

### Steps to Reproduce

Click on Raid Day ics

### Device

iPhone 13 Pro Max

### Operating System

iOS 18.0

**Comment by ArmandAgopian** [comment]
The error is on Leek Duck for incorrectly marking it as Event instead of Raid Day. Closing.

**Comment by othyn** [comment]
For some reason the build didn't kick off last night, as it appears LeekDuck corrected it. Just pushed a new build, so your calendar client should pickup the change shortly, as its now pulled through as a Raid Day correctly:

https://github.com/othyn/go-calendar/blob/main/dist/gocal__raid_day.ics
