### ISSUE TITLE
Access past events

### ISSUE THREAD

**Issue by Nekomajin42** [othyn/go-calendar#8]
### Description

Is it possible to compile another set of files to include events from the past? I would like to access all events, not just future and ongoig ones.

### Desired Behavior

I am creating a dedicated calendar app for Android. It would be good if it could act like an archive too.

**Comment by othyn** [comment]
The tools I use to generate the calendar are:

- https://github.com/bigfoott/ScrapedDuck
- https://github.com/bigfoott/ScrapedDuck/wiki/Events

I would start there to look at archival data, I don't plan on adding archival data at this time as this repo is simply morphing upstream data into an iCal format at runtime. It retains no persistent storage within itself, and I don't plan on adding it to this repo at this time as it sits outside of the scope of what this repo aims to achieve.
