### ISSUE TITLE
Mobile Friendly / More space efficient

### ISSUE THREAD

**Issue by Boby360** [othyn/go-calendar#9]
### Description

Right now calendar events show up as [Raid Hour] Mon Raid Hour.
There is a lot of repetition and it wastes space on calendars.

### Desired Behavior

It would be great if there would be a "mobile" version or a "short" version of the calendars that would remove one of these references.

Even having [CD] [RH], etc would be a significant improvement.
Although ss the individual calendars can have unique colors, it already will can have a unique identifier and I don't even see a need for them in the "customized" calendars.

### Additional Context

This just adds a lot of clutter to my calendar. Both on my Laptop and my S23.
On my S23 in the Samsung Calendar, [Raid Hour] doesn't even fit on one line, making it a significant impact.

**Comment by othyn** [comment]
Don't mind shrinking the text to acronyms instead.

I _think_ the code just injects the type into the event name, it's been a _long_ time since I last looked at this repo. If that's the case then it'll be a small ish change.

Do you have any screen shots as reference?

**Comment by Boby360** [comment]
![Screenshot_20240203_155856_Calendar.png](https://github.com/othyn/go-calendar/assets/1607258/f5fa7b3f-9805-473c-b65e-2de1b4586215)

This is what it looks like on my s23 calendar

**Comment by Boby360** [comment]
This is what it looks like in Outlook in the largest view possible on a 1920x1080 screen.
![image](https://github.com/othyn/go-calendar/assets/1607258/e0ced524-1a84-4168-91c4-5c2d65259b51)

**Comment by Boby360** [comment]
And this would be a traditional view 
![image](https://github.com/othyn/go-calendar/assets/1607258/dd6b822c-7692-481b-bd1e-a7d5d8f41242)

**Comment by Boby360** [comment]
Sample alterations in the smaller outlook view:
![image](https://github.com/othyn/go-calendar/assets/1607258/0fef3e51-6d2b-4b42-8ca2-0b813e9c7a4d)

**Comment by Boby360** [comment]
What those look like on S23
![Screenshot_20240204_112932_Calendar](https://github.com/othyn/go-calendar/assets/1607258/95efa2ae-a43a-4b10-a437-0183248fb1d2)

**Comment by othyn** [comment]
Super thank you, provides good context for what is being chopped off. I'll take a look and see if the type prefixes can be easily collapsed down to an abbreviation.

**Comment by othyn** [comment]
Done. The calendar now has all the event types as acronyms. See [v2.4.0](https://github.com/othyn/go-calendar/releases/tag/v2.4.0) which is live on [gocalendar.info](https://gocalendar.info)
